### ISSUE TITLE
Disable text lookup while sticky search is enabled.

### ISSUE THREAD

**Issue by epistularum** [wareya/nazeka#21]
Most of the time when I enable sticky search is too scroll through a definition but words get looked up when you're trying to reach the pop up window.

Note: Applying a pop up key obviously solves this.

**Comment by wareya** [comment]
I tend to use the mining UI for this even though I'm not actually mining.

**Comment by epistularum** [comment]
What about combining the mining UI with sticky mode since they offer a similar feature?

**Comment by wareya** [comment]
Mining UI needs to not change when mousing over stuff, since you can look stuff up in it as well.

**Comment by epistularum** [comment]
Users should be allowed to search within the sticky mode as well, don't you think?

**Comment by wareya** [comment]
Sticky mode is supposed to update when the mouse scans over different text, so...

**Comment by epistularum** [comment]
For j-j dictionaries it might be useful to look-up unknown words directly in the sticky window.

I feel like using the mining UI to scroll through definitions when not using a keyboard shortcut for look-up is strange and not intuitive.

**Comment by wareya** [comment]
I can pretty easily make it so mousing over the sticky window doesn't do anything, but I have no easy way of letting you do lookups inside of the sticky window. What happens when you press the left/right arrow key? Does it seek left/right in the sticky window or the normal window?

**Comment by epistularum** [comment]
I'm having some issues interpreting what you just wrote.
Are you saying that there is two windows opened at the same time?

**Comment by wareya** [comment]
Well, that's how looking stuff up in the mining UI works. If you were to look something up in the sticky window, then either you'd get a second definitions list (so you can look up multiple words in the same sentence), or it would replace the sticky window's contents entirely (making it so you could only look up a single thing, and now you have to look the original thing up again).

**Comment by epistularum** [comment]
Ok I understood.

We could combine the mining UI with sticky mode by keeping the sticky mode behavior where the main windows updates when we look up words on the page but looking up a word in the window itself pops up another window.

**Comment by wareya** [comment]
That would be the first option, and I don't have an easy way of doing it because so many things (including keyboard controls) assume that there's exactly one real definitions popup.

**Comment by wareya** [comment]
Closing this because it's too far detached from how nazeka handles the popup window internally.
