### ISSUE TITLE
Better visual cues for dictionary titles.

### ISSUE THREAD

**Issue by epistularum** [wareya/nazeka#22]
As it is it's quite difficult to make up different dictionary definitions at a glance because dictionary titles have the same font color/size as the definitions.
Perhaps modifying the styling of the dictionary titles to make them stand out a bit more would be a great addition.

Also it would be better to have consistent styling between jmdict and epwing titles.
Currently jmdict title is stylized as such:
````
jmdict:<definition>
````

When epwing titles are stylized as such:
````
―<title>―
<definition>
````
Example:
![example](https://i.imgur.com/sVYudbA.png)

**Comment by wareya** [comment]
Added
