### ISSUE TITLE
[Epwing] 彼処[あそこ] Doesn't get match correctly.

### ISSUE THREAD

**Issue by epistularum** [wareya/nazeka#25]
In jmdict あそこ and かしこ are under the same entry while en Kenkyuusha/Shinmeikai those are two different entries. Which somehow results in かしこ being displayed instead of あそこ.

The fix would be either matching the epwing definitions to the first jmdict reading or including all epwing entries (sorted according to the jmdict order)

![](https://i.imgur.com/Lw4I6EH.png)

**Comment by wareya** [comment]
These dictionaries don't have 彼処 as spellings of あそこ, only of かしこ. Daijirin, Daijisen, and Koujien do, though.
