### ISSUE TITLE
Doesn't work on android in reader view mode

### ISSUE THREAD

**Issue by n00p3** [wareya/nazeka#3]
firefox version: 59.0.2
nazeka version: 0.1.8

**Comment by wareya** [comment]
This is a known problem, just not written down anywhere. Unfortunately "content scripts" (something nontrivial modern firefox extensions need to use) can't be loaded in reader view pages for some reason. Also reader view has really aggressive CSS, so the popup would look really bad until Shadow DOM lands and I make nazeka use it to keep page CSS from affecting the popup.

https://bugzilla.mozilla.org/show_bug.cgi?id=1371786

https://github.com/philc/vimium/issues/2609#issuecomment-324269445

https://bugzilla.mozilla.org/show_bug.cgi?id=1286387

**Comment by Akariiiii** [comment]
Hi, are you planning to add this feature soon ? I really love your add-on as it works on firefox android. It will be a lot better if it works on the reader mode as well.

**Comment by wareya** [comment]
I'm incapable of supporting reader view mode until Mozilla changes how it works.

**Comment by Akariiiii** [comment]
I read the bug comments. So they are still not planning to support content scripts in reader mode ? What a stupid decision since a lot of people use reader mode nowadays

**Comment by wareya** [comment]
Closing this because I'll never be able to fix it.
