### ISSUE TITLE
Add settings import/export

### ISSUE THREAD

**Issue by wareya** [wareya/nazeka#4]
Firefox keeps clearing my settings because of Firefox bugs involving temporary/debug extensions, so I have to do this for my own sanity.

**Comment by wareya** [comment]
done

**Comment by psychodelicwasabi** [comment]
Sorry for the incredibly late answer, I had some internet problems. But I'm
already using it, thank you very much, you're a life saver! That's exactly
what I needed. I recommended it to all my friends, hope you keep it up!
Good job and thank you again!
