### ISSUE TITLE
Unable to mine cards or play audio

### ISSUE THREAD

**Issue by MasonRepo** [wareya/nazeka#55]
Hello,

I was curious if anyone else had a similar problem happen for them as well. I'm currently using Nazeka's live mining feature with and whenever I try and mine a word an error pops up that says this: https://i.imgur.com/1hselnq.png

It was working up until yesterday, I don't believe anything updated or anything like that so any help would be greatly appreciated!

**Comment by wareya** [comment]
I'll check this out some time during this week.

**Comment by MasonRepo** [comment]
Thank you much!  Some things I've tried is adding a CORS extenstion and enabling that as well as double checking that the AnkiConnect local host is still running (it is).  It does play the audio for some words like ない and some particles like を and such but nothing I can pinpoint as to why those specific ones.  Also I disabled my firewall and removed my adblocker.  Hopefully that helps find out what could be the issue!

**Comment by wareya** [comment]
Looks like the languagepod101 asset servers aren't responding. See also: https://github.com/FooSoft/yomichan/issues/1574

**Comment by MasonRepo** [comment]
Hmmm that's interesting.  Would not being able to connect to their servers cause Nazeka to not be able to connect to ankiconnect's localhost for mining?  Either way I'll wait for a while to see how things pan out and will close the ticket it if it resolves itself!

**Comment by MasonRepo** [comment]
JapanesePod101 is up which has fixed the mining issue.
