### ISSUE TITLE
Is there anyway I can contact you?

### ISSUE THREAD

**Issue by phuongdtvd** [wareya/nazeka#56]
I'm really sorry for using the issue feature like this, but I really like the extension and have been wanting to contact you to ask for some advices but have no real way to do it and I really apologize for having to resort to using this. I have been wanting to build a somewhat similar web app like nazeka but since I'm really new to this stuff I don't know how to handle certain things, especially the huge JMdict json file. So I was wondering if there's a discord or something where I ask you for some pointers if possible? Again I'm really sorry and if you find this too annoying you can just close it.

**Comment by wareya** [comment]
I'm busy right now, but sure, you can just email me.

**Comment by phuongdtvd** [comment]
Thank you! Sorry for bothering you
